---
name: NPM Publish

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC trusted publishing to NPM
  contents: write # Required for adding the tarball to the GitHub release

jobs:
  publish-npm:
    name: Publish Node-RED package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: "npm" # Corrected property name for setup-node caching

      - name: npm Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create npm package tarball
        run: |
          TGZ="$(npm pack)"
          echo "TGZ=$TGZ" >> $GITHUB_ENV

      - name: Upload tgz to GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.event.release.tag_name }}
        run: |
          # If it's a release event, or if the current git ref is a tag (e.g. v1.2.3)
          if [ -n "$TAG" ]; then
            gh release upload "$TAG" "$TGZ" --clobber
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            gh release upload "${{ github.ref_name }}" "$TGZ" --clobber
          else
            echo "Not a release or tagged ref, skipping asset upload."
          fi

      - name: npm Publish
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to Node-RED Library
        uses: Hacksore/node-red-flow@v2
        with:
          repo: ${{ github.repository }}
